version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todolist_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db # Força o TypeORM a olhar para o contêiner do banco

  db:
    image: postgres:15-alpine
    container_name: todolist_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha12
      POSTGRES_DB: flow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todolist_frontend
    ports:
      - "80:80"
    depends_on:
      - api